### ISSUE TITLE
shiftOneBitLeft will not work if there is a leading 0 chunk

### ISSUE THREAD

**Issue by neimanpinchas** [maitag/littleBigInt#2]
I had a case where 
38822172018368467232221876517022647746670688902647604098966333013322460858113 << 1 (+1)
eq
19748299418078836752658260529701341566706385472474926178203874022688356896259

when I tried to make a simple test case, I received the proper answer of 
77644344036736934464443753034045295493341377805295208197932666026644921716227

After digging into the binaryrep and than into the chunks I found that the good number was
1793-3761-15579-17519-5200-1158-26453-3914-673-29035-13051-24688-19726-10648-5501-18700-21972 end:17
after shifting
3587_7522_31158_2270_10401_2316_20138_7829_1346_25302_26103_16608_6685_21297_11002_4632_11177_1 end:18

my bad input
1793-3761-15579-17519-5200-1158-26453-3914-673-29035-13051-24688-19726-10648-5501-18700-21972-0 end: 17
bad output
3586-7522-31158-2270-10401-2316-20138-7829-1346-25302-26103-16608-6685-21297-11002-4632-11177-0-1 end:18

since the siftleft function is relying on the ~arraylength~ EDIT, on the end variable which is one to less and not on other kind of check for nonsignificant zeros, the final push is naive and the behavior is well understood.
```haxe
	public function shiftOneBitLeft() {
		if (this != null) {
			var v:LittleInt = 0;
			for (i in 0...length) {
				v = (get(i) << 1) | ((v & LittleIntChunks.UPPESTBIT > 0) ? 1 : 0) ;
				set(i, v & LittleIntChunks.BITMASK);
			}
			if (v & LittleIntChunks.UPPESTBIT > 0) push(1);
		}
	}
```

Question is what is the proper method of getting past this probelm, fixing the implementation of SHL, or find another way to ensure we never get invalid chunks.

Sorry of being so investigating, I ported an app from JS to Haxe and I couldn't get it to work, I've been trying thx.core, issues with float rounding, I've tried yesterday haxe-crypto BigInteger got an unimplemented error somewhere in division, I've been thinking at night, making a decision types-macros or proper math, is as painfull as being forced to use pen and paper becuase computers cant do precise math, I really need to have BigInt work in haxe for every rational number in the universe

**Comment by neimanpinchas** [comment]
I tried truncateZeroChunks(true)
However since end is 17 it doesnt try to remove it,

**Comment by neimanpinchas** [comment]
To be honest, for now I've just managed to patch thx, not sure he will accept my PR, but since my app is working now I might step down for some time, perheps until when performance will become an issue, so I will need to benfit from the optimizations in this great library.
Another benefit of your lib is the complete operators and casting and conversion utilities.

**Comment by maitag** [comment]
Mhm, not really understand what the problem is in bitshifting there. It never should produce an empty chunk, so maybe there was some one inside the number before ?
Pls tell me if you find a operation what still produce empty-chunks (all should be trunkate arised zero chunks automatically!)

**Comment by maitag** [comment]
oh, can it be that you have some "division" before ? ... i am think after this line:
<https://github.com/maitag/littleBigInt/blob/master/src/BigInt.hx#L667>
a `q.truncateZeroChunks(false);` is also need.
(hope this will fix the problem and it is not left at more places...
 if you found another one pls tell me!)

**Comment by maitag** [comment]
i am think it is also need for `~a`, `a--`, `a++`, `--a`, `++a` operations (after `subtractLittle`)

**Comment by maitag** [comment]
Anyway, pls try latest commit <https://github.com/maitag/littleBigInt/commit/885619668de4b9c6a07a3fda65001bf668b8daf3> to check that all is working now!
Please gimme also your sample (at what point it was get stuck by producing that zerochunks and the bitshifting into follow), so i can put it into the unit-testcode.
(apropos, to have and additional prove/unit-test for multiplication and division,
 we could extend the "pi"-benchmark to compare the result with a precomputed value)
